INSERT INTO EXERCISE(NAME,
                     CATEGORY,
                     DEMO_URL,
                     GENERAL_MUSCLE_GROUP,
                     TARGET_MUSCLE_GROUP,
                     LOC_INDOORS,
                     LOC_OUTDOORS,
                     EQ_JUMP_ROPE,
                     EQ_PULLUP_BAR,
                     EQ_WEIGHTS,
                     EQ_KETTLE_BELLS,
                     EQ_HEAVY_OBJECT,
                     EQ_TRX,
                     EQ_MED_BALL,
                     EQ_BOX,
                     EQ_SQUAT_RACK,
                     EQ_TREADMILL,
                     EQ_TRACK,
                     EQ_TRAIL,
                     EQ_HILLS,
                     EQ_POOL,
                     EQ_BIKE,
                     EQ_ROW_MACHINE)
          VALUES('arm curls',
                 'strength', -- strength, athleticism, endurance, warmup, cooldown, mind
                 'https://www.youtube.com/watch?v=kwG2ipFRgfo',
                 'arms',
                 'biceps',
                 1, -- LOC_INDOORS,
                 1, -- LOC_OUTDOORS,
                 0, -- EQ_JUMP_ROPE,
                 0, -- EQ_PULLUP_BAR,
                 1, -- EQ_WEIGHTS,
                 1, -- EQ_KETTLE_BELLS,
                 1, -- EQ_HEAVY_OBJECT,
                 1, -- EQ_TRX,
                 0, -- EQ_MED_BALL,
                 0, -- EQ_BOX,
                 0, -- EQ_SQUAT_RACK,
                 0, -- EQ_TREADMILL,
                 0, -- EQ_TRACK,
                 0, -- EQ_TRAIL,
                 0, -- EQ_HILLS,
                 0, -- EQ_POOL,
                 0, -- EQ_BIKE,
                 0); -- EQ_ROW_MACHINE


INSERT INTO EXERCISE(NAME,
                     CATEGORY,
                     DEMO_URL,
                     GENERAL_MUSCLE_GROUP,
                     TARGET_MUSCLE_GROUP,
                     LOC_INDOORS,
                     LOC_OUTDOORS,
                     EQ_JUMP_ROPE,
                     EQ_PULLUP_BAR,
                     EQ_WEIGHTS,
                     EQ_KETTLE_BELLS,
                     EQ_HEAVY_OBJECT,
                     EQ_TRX,
                     EQ_MED_BALL,
                     EQ_BOX,
                     EQ_SQUAT_RACK,
                     EQ_TREADMILL,
                     EQ_TRACK,
                     EQ_TRAIL,
                     EQ_HILLS,
                     EQ_POOL,
                     EQ_BIKE,
                     EQ_ROW_MACHINE)
          VALUES('back extension',
                 'strength', -- strength, athleticism, endurance, warmup, cooldown, mind
                 'https://www.youtube.com/watch?v=Bw9YuQTTc58', 
                 'back',
                 'back',
                 1, -- LOC_INDOORS,
                 1, -- LOC_OUTDOORS,
                 0, -- EQ_JUMP_ROPE,
                 0, -- EQ_PULLUP_BAR,
                 0, -- EQ_WEIGHTS,
                 0, -- EQ_KETTLE_BELLS,
                 0, -- EQ_HEAVY_OBJECT,
                 0, -- EQ_TRX,
                 0, -- EQ_MED_BALL,
                 0, -- EQ_BOX,
                 0, -- EQ_SQUAT_RACK,
                 0, -- EQ_TREADMILL,
                 0, -- EQ_TRACK,
                 0, -- EQ_TRAIL,
                 0, -- EQ_HILLS,
                 0, -- EQ_POOL,
                 0, -- EQ_BIKE,
                 0); -- EQ_ROW_MACHINE

INSERT INTO EXERCISE(NAME,
                     CATEGORY,
                     DEMO_URL,
                     GENERAL_MUSCLE_GROUP,
                     TARGET_MUSCLE_GROUP,
                     LOC_INDOORS,
                     LOC_OUTDOORS,
                     EQ_JUMP_ROPE,
                     EQ_PULLUP_BAR,
                     EQ_WEIGHTS,
                     EQ_KETTLE_BELLS,
                     EQ_HEAVY_OBJECT,
                     EQ_TRX,
                     EQ_MED_BALL,
                     EQ_BOX,
                     EQ_SQUAT_RACK,
                     EQ_TREADMILL,
                     EQ_TRACK,
                     EQ_TRAIL,
                     EQ_HILLS,
                     EQ_POOL,
                     EQ_BIKE,
                     EQ_ROW_MACHINE)
          VALUES('bear crawl',
                 'athleticism', -- strength, athleticism, endurance, warmup, cooldown, mind
                 'https://www.youtube.com/watch?v=WMXbyYpZ9oY',
                 'full body',
                 'full body',
                 1, -- LOC_INDOORS,
                 1, -- LOC_OUTDOORS,
                 0, -- EQ_JUMP_ROPE,
                 0, -- EQ_PULLUP_BAR,
                 0, -- EQ_WEIGHTS,
                 0, -- EQ_KETTLE_BELLS,
                 0, -- EQ_HEAVY_OBJECT,
                 0, -- EQ_TRX,
                 0, -- EQ_MED_BALL,
                 0, -- EQ_BOX,
                 0, -- EQ_SQUAT_RACK,
                 0, -- EQ_TREADMILL,
                 0, -- EQ_TRACK,
                 0, -- EQ_TRAIL,
                 0, -- EQ_HILLS,
                 0, -- EQ_POOL,
                 0, -- EQ_BIKE,
                 0); -- EQ_ROW_MACHINE

INSERT INTO EXERCISE(NAME,
                     CATEGORY,
                     DEMO_URL,
                     GENERAL_MUSCLE_GROUP,
                     TARGET_MUSCLE_GROUP,
                     LOC_INDOORS,
                     LOC_OUTDOORS,
                     EQ_JUMP_ROPE,
                     EQ_PULLUP_BAR,
                     EQ_WEIGHTS,
                     EQ_KETTLE_BELLS,
                     EQ_HEAVY_OBJECT,
                     EQ_TRX,
                     EQ_MED_BALL,
                     EQ_BOX,
                     EQ_SQUAT_RACK,
                     EQ_TREADMILL,
                     EQ_TRACK,
                     EQ_TRAIL,
                     EQ_HILLS,
                     EQ_POOL,
                     EQ_BIKE,
                     EQ_ROW_MACHINE)
          VALUES('belly crawl',
                 'athleticism', -- strength, athleticism, endurance, warmup, cooldown, mind
                 'https://www.youtube.com/watch?v=cLwS1xkOLas',
                 'upper body',
                 'upper body',
                 1, -- LOC_INDOORS,
                 1, -- LOC_OUTDOORS,
                 0, -- EQ_JUMP_ROPE,
                 0, -- EQ_PULLUP_BAR,
                 0, -- EQ_WEIGHTS,
                 0, -- EQ_KETTLE_BELLS,
                 0, -- EQ_HEAVY_OBJECT,
                 0, -- EQ_TRX,
                 0, -- EQ_MED_BALL,
                 0, -- EQ_BOX,
                 0, -- EQ_SQUAT_RACK,
                 0, -- EQ_TREADMILL,
                 0, -- EQ_TRACK,
                 0, -- EQ_TRAIL,
                 0, -- EQ_HILLS,
                 0, -- EQ_POOL,
                 0, -- EQ_BIKE,
                 0); -- EQ_ROW_MACHINE


INSERT INTO EXERCISE(NAME,
                     CATEGORY,
                     DEMO_URL,
                     GENERAL_MUSCLE_GROUP,
                     TARGET_MUSCLE_GROUP,
                     LOC_INDOORS,
                     LOC_OUTDOORS,
                     EQ_JUMP_ROPE,
                     EQ_PULLUP_BAR,
                     EQ_WEIGHTS,
                     EQ_KETTLE_BELLS,
                     EQ_HEAVY_OBJECT,
                     EQ_TRX,
                     EQ_MED_BALL,
                     EQ_BOX,
                     EQ_SQUAT_RACK,
                     EQ_TREADMILL,
                     EQ_TRACK,
                     EQ_TRAIL,
                     EQ_HILLS,
                     EQ_POOL,
                     EQ_BIKE,
                     EQ_ROW_MACHINE)
          VALUES('bodyweight circuit',
                 'strength', -- strength, athleticism, endurance, warmup, cooldown, mind
                 '',
                 'full body',
                 'full body',
                 1, -- LOC_INDOORS,
                 1, -- LOC_OUTDOORS,
                 0, -- EQ_JUMP_ROPE,
                 1, -- EQ_PULLUP_BAR,
                 0, -- EQ_WEIGHTS,
                 0, -- EQ_KETTLE_BELLS,
                 0, -- EQ_HEAVY_OBJECT,
                 1, -- EQ_TRX,
                 0, -- EQ_MED_BALL,
                 1, -- EQ_BOX,
                 0, -- EQ_SQUAT_RACK,
                 0, -- EQ_TREADMILL,
                 0, -- EQ_TRACK,
                 0, -- EQ_TRAIL,
                 0, -- EQ_HILLS,
                 0, -- EQ_POOL,
                 0, -- EQ_BIKE,
                 0); -- EQ_ROW_MACHINE


INSERT INTO EXERCISE(NAME,
                     CATEGORY,
                     DEMO_URL,
                     GENERAL_MUSCLE_GROUP,
                     TARGET_MUSCLE_GROUP,
                     LOC_INDOORS,
                     LOC_OUTDOORS,
                     EQ_JUMP_ROPE,
                     EQ_PULLUP_BAR,
                     EQ_WEIGHTS,
                     EQ_KETTLE_BELLS,
                     EQ_HEAVY_OBJECT,
                     EQ_TRX,
                     EQ_MED_BALL,
                     EQ_BOX,
                     EQ_SQUAT_RACK,
                     EQ_TREADMILL,
                     EQ_TRACK,
                     EQ_TRAIL,
                     EQ_HILLS,
                     EQ_POOL,
                     EQ_BIKE,
                     EQ_ROW_MACHINE)
          VALUES('bodyweight squat',
                 'strength', -- strength, athleticism, endurance, warmup, cooldown, mind
                 '',
                 'lower body',
                 'legs',
                 1, -- LOC_INDOORS,
                 1, -- LOC_OUTDOORS,
                 0, -- EQ_JUMP_ROPE,
                 0, -- EQ_PULLUP_BAR,
                 0, -- EQ_WEIGHTS,
                 0, -- EQ_KETTLE_BELLS,
                 0, -- EQ_HEAVY_OBJECT,
                 1, -- EQ_TRX,
                 0, -- EQ_MED_BALL,
                 0, -- EQ_BOX,
                 0, -- EQ_SQUAT_RACK,
                 0, -- EQ_TREADMILL,
                 0, -- EQ_TRACK,
                 0, -- EQ_TRAIL,
                 0, -- EQ_HILLS,
                 0, -- EQ_POOL,
                 0, -- EQ_BIKE,
                 0); -- EQ_ROW_MACHINE



INSERT INTO EXERCISE(NAME,
                     CATEGORY,
                     DEMO_URL,
                     GENERAL_MUSCLE_GROUP,
                     TARGET_MUSCLE_GROUP,
                     LOC_INDOORS,
                     LOC_OUTDOORS,
                     EQ_JUMP_ROPE,
                     EQ_PULLUP_BAR,
                     EQ_WEIGHTS,
                     EQ_KETTLE_BELLS,
                     EQ_HEAVY_OBJECT,
                     EQ_TRX,
                     EQ_MED_BALL,
                     EQ_BOX,
                     EQ_SQUAT_RACK,
                     EQ_TREADMILL,
                     EQ_TRACK,
                     EQ_TRAIL,
                     EQ_HILLS,
                     EQ_POOL,
                     EQ_BIKE,
                     EQ_ROW_MACHINE)
          VALUES('box jump',
                 'strength', -- strength, athleticism, endurance, warmup, cooldown, mind
                 '',
                 'lower body',
                 'legs',
                 1, -- LOC_INDOORS,
                 1, -- LOC_OUTDOORS,
                 0, -- EQ_JUMP_ROPE,
                 0, -- EQ_PULLUP_BAR,
                 0, -- EQ_WEIGHTS,
                 0, -- EQ_KETTLE_BELLS,
                 0, -- EQ_HEAVY_OBJECT,
                 0, -- EQ_TRX,
                 0, -- EQ_MED_BALL,
                 1, -- EQ_BOX,
                 0, -- EQ_SQUAT_RACK,
                 0, -- EQ_TREADMILL,
                 0, -- EQ_TRACK,
                 0, -- EQ_TRAIL,
                 0, -- EQ_HILLS,
                 0, -- EQ_POOL,
                 0, -- EQ_BIKE,
                 0); -- EQ_ROW_MACHINE

INSERT INTO EXERCISE(NAME,
                     CATEGORY,
                     DEMO_URL,
                     GENERAL_MUSCLE_GROUP,
                     TARGET_MUSCLE_GROUP,
                     LOC_INDOORS,
                     LOC_OUTDOORS,
                     EQ_JUMP_ROPE,
                     EQ_PULLUP_BAR,
                     EQ_WEIGHTS,
                     EQ_KETTLE_BELLS,
                     EQ_HEAVY_OBJECT,
                     EQ_TRX,
                     EQ_MED_BALL,
                     EQ_BOX,
                     EQ_SQUAT_RACK,
                     EQ_TREADMILL,
                     EQ_TRACK,
                     EQ_TRAIL,
                     EQ_HILLS,
                     EQ_POOL,
                     EQ_BIKE,
                     EQ_ROW_MACHINE)
          VALUES('box jump burpee',
                 'athleticism', -- strength, athleticism, endurance, warmup, cooldown, mind
                 '',
                 'full body',
                 'full body',
                 1, -- LOC_INDOORS,
                 1, -- LOC_OUTDOORS,
                 0, -- EQ_JUMP_ROPE,
                 0, -- EQ_PULLUP_BAR,
                 0, -- EQ_WEIGHTS,
                 0, -- EQ_KETTLE_BELLS,
                 0, -- EQ_HEAVY_OBJECT,
                 0, -- EQ_TRX,
                 0, -- EQ_MED_BALL,
                 1, -- EQ_BOX,
                 0, -- EQ_SQUAT_RACK,
                 0, -- EQ_TREADMILL,
                 0, -- EQ_TRACK,
                 0, -- EQ_TRAIL,
                 0, -- EQ_HILLS,
                 0, -- EQ_POOL,
                 0, -- EQ_BIKE,
                 0); -- EQ_ROW_MACHINE



INSERT INTO EXERCISE(NAME,
                     CATEGORY,
                     DEMO_URL,
                     GENERAL_MUSCLE_GROUP,
                     TARGET_MUSCLE_GROUP,
                     LOC_INDOORS,
                     LOC_OUTDOORS,
                     EQ_JUMP_ROPE,
                     EQ_PULLUP_BAR,
                     EQ_WEIGHTS,
                     EQ_KETTLE_BELLS,
                     EQ_HEAVY_OBJECT,
                     EQ_TRX,
                     EQ_MED_BALL,
                     EQ_BOX,
                     EQ_SQUAT_RACK,
                     EQ_TREADMILL,
                     EQ_TRACK,
                     EQ_TRAIL,
                     EQ_HILLS,
                     EQ_POOL,
                     EQ_BIKE,
                     EQ_ROW_MACHINE)
          VALUES('brazilian ab twist',
                 'strength', -- strength, athleticism, endurance, warmup, cooldown, mind
                 'https://www.youtube.com/watch?v=iUk5T87cf34',
                 'core',
                 'abs',
                 1, -- LOC_INDOORS,
                 1, -- LOC_OUTDOORS,
                 0, -- EQ_JUMP_ROPE,
                 0, -- EQ_PULLUP_BAR,
                 0, -- EQ_WEIGHTS,
                 0, -- EQ_KETTLE_BELLS,
                 0, -- EQ_HEAVY_OBJECT,
                 0, -- EQ_TRX,
                 0, -- EQ_MED_BALL,
                 0, -- EQ_BOX,
                 0, -- EQ_SQUAT_RACK,
                 0, -- EQ_TREADMILL,
                 0, -- EQ_TRACK,
                 0, -- EQ_TRAIL,
                 0, -- EQ_HILLS,
                 0, -- EQ_POOL,
                 0, -- EQ_BIKE,
                 0); -- EQ_ROW_MACHINE




INSERT INTO EXERCISE(NAME,
                     CATEGORY,
                     DEMO_URL,
                     GENERAL_MUSCLE_GROUP,
                     TARGET_MUSCLE_GROUP,
                     LOC_INDOORS,
                     LOC_OUTDOORS,
                     EQ_JUMP_ROPE,
                     EQ_PULLUP_BAR,
                     EQ_WEIGHTS,
                     EQ_KETTLE_BELLS,
                     EQ_HEAVY_OBJECT,
                     EQ_TRX,
                     EQ_MED_BALL,
                     EQ_BOX,
                     EQ_SQUAT_RACK,
                     EQ_TREADMILL,
                     EQ_TRACK,
                     EQ_TRAIL,
                     EQ_HILLS,
                     EQ_POOL,
                     EQ_BIKE,
                     EQ_ROW_MACHINE)
          VALUES('burpee',
                 'athleticism', -- strength, athleticism, endurance, warmup, cooldown, mind
                 '',
                 'full body',
                 'full body',
                 1, -- LOC_INDOORS,
                 1, -- LOC_OUTDOORS,
                 0, -- EQ_JUMP_ROPE,
                 0, -- EQ_PULLUP_BAR,
                 0, -- EQ_WEIGHTS,
                 0, -- EQ_KETTLE_BELLS,
                 0, -- EQ_HEAVY_OBJECT,
                 0, -- EQ_TRX,
                 0, -- EQ_MED_BALL,
                 0, -- EQ_BOX,
                 0, -- EQ_SQUAT_RACK,
                 0, -- EQ_TREADMILL,
                 0, -- EQ_TRACK,
                 0, -- EQ_TRAIL,
                 0, -- EQ_HILLS,
                 0, -- EQ_POOL,
                 0, -- EQ_BIKE,
                 0); -- EQ_ROW_MACHINE


INSERT INTO EXERCISE(NAME,
                     CATEGORY,
                     DEMO_URL,
                     GENERAL_MUSCLE_GROUP,
                     TARGET_MUSCLE_GROUP,
                     LOC_INDOORS,
                     LOC_OUTDOORS,
                     EQ_JUMP_ROPE,
                     EQ_PULLUP_BAR,
                     EQ_WEIGHTS,
                     EQ_KETTLE_BELLS,
                     EQ_HEAVY_OBJECT,
                     EQ_TRX,
                     EQ_MED_BALL,
                     EQ_BOX,
                     EQ_SQUAT_RACK,
                     EQ_TREADMILL,
                     EQ_TRACK,
                     EQ_TRAIL,
                     EQ_HILLS,
                     EQ_POOL,
                     EQ_BIKE,
                     EQ_ROW_MACHINE)
          VALUES('burpee pull-up',
                 'strength', -- strength, athleticism, endurance, warmup, cooldown, mind
                 '',
                 'full body',
                 'full body',
                 1, -- LOC_INDOORS,
                 1, -- LOC_OUTDOORS,
                 0, -- EQ_JUMP_ROPE,
                 0, -- EQ_PULLUP_BAR,
                 0, -- EQ_WEIGHTS,
                 0, -- EQ_KETTLE_BELLS,
                 0, -- EQ_HEAVY_OBJECT,
                 0, -- EQ_TRX,
                 0, -- EQ_MED_BALL,
                 0, -- EQ_BOX,
                 0, -- EQ_SQUAT_RACK,
                 0, -- EQ_TREADMILL,
                 0, -- EQ_TRACK,
                 0, -- EQ_TRAIL,
                 0, -- EQ_HILLS,
                 0, -- EQ_POOL,
                 0, -- EQ_BIKE,
                 0); -- EQ_ROW_MACHINE


INSERT INTO EXERCISE(NAME,
                     CATEGORY,
                     DEMO_URL,
                     GENERAL_MUSCLE_GROUP,
                     TARGET_MUSCLE_GROUP,
                     LOC_INDOORS,
                     LOC_OUTDOORS,
                     EQ_JUMP_ROPE,
                     EQ_PULLUP_BAR,
                     EQ_WEIGHTS,
                     EQ_KETTLE_BELLS,
                     EQ_HEAVY_OBJECT,
                     EQ_TRX,
                     EQ_MED_BALL,
                     EQ_BOX,
                     EQ_SQUAT_RACK,
                     EQ_TREADMILL,
                     EQ_TRACK,
                     EQ_TRAIL,
                     EQ_HILLS,
                     EQ_POOL,
                     EQ_BIKE,
                     EQ_ROW_MACHINE)
          VALUES('chest pass',
                 'strength', -- strength, athleticism, endurance, warmup, cooldown, mind
                 'https://www.youtube.com/watch?v=FUdcjZ0weic',
                 'upper body',
                 'chest',
                 1, -- LOC_INDOORS,
                 1, -- LOC_OUTDOORS,
                 0, -- EQ_JUMP_ROPE,
                 0, -- EQ_PULLUP_BAR,
                 0, -- EQ_WEIGHTS,
                 0, -- EQ_KETTLE_BELLS,
                 0, -- EQ_HEAVY_OBJECT,
                 0, -- EQ_TRX,
                 1, -- EQ_MED_BALL,
                 0, -- EQ_BOX,
                 0, -- EQ_SQUAT_RACK,
                 0, -- EQ_TREADMILL,
                 0, -- EQ_TRACK,
                 0, -- EQ_TRAIL,
                 0, -- EQ_HILLS,
                 0, -- EQ_POOL,
                 0, -- EQ_BIKE,
                 0); -- EQ_ROW_MACHINE

INSERT INTO EXERCISE(NAME,
                     CATEGORY,
                     DEMO_URL,
                     GENERAL_MUSCLE_GROUP,
                     TARGET_MUSCLE_GROUP,
                     LOC_INDOORS,
                     LOC_OUTDOORS,
                     EQ_JUMP_ROPE,
                     EQ_PULLUP_BAR,
                     EQ_WEIGHTS,
                     EQ_KETTLE_BELLS,
                     EQ_HEAVY_OBJECT,
                     EQ_TRX,
                     EQ_MED_BALL,
                     EQ_BOX,
                     EQ_SQUAT_RACK,
                     EQ_TREADMILL,
                     EQ_TRACK,
                     EQ_TRAIL,
                     EQ_HILLS,
                     EQ_POOL,
                     EQ_BIKE,
                     EQ_ROW_MACHINE)
          VALUES('chore',
                 'active rest', -- strength, athleticism, endurance, warmup, cooldown, mind, active rest
                 '',
                 'full body',
                 'full body',
                 1, -- LOC_INDOORS,
                 1, -- LOC_OUTDOORS,
                 0, -- EQ_JUMP_ROPE,
                 0, -- EQ_PULLUP_BAR,
                 0, -- EQ_WEIGHTS,
                 0, -- EQ_KETTLE_BELLS,
                 0, -- EQ_HEAVY_OBJECT,
                 0, -- EQ_TRX,
                 0, -- EQ_MED_BALL,
                 0, -- EQ_BOX,
                 0, -- EQ_SQUAT_RACK,
                 0, -- EQ_TREADMILL,
                 0, -- EQ_TRACK,
                 0, -- EQ_TRAIL,
                 0, -- EQ_HILLS,
                 0, -- EQ_POOL,
                 0, -- EQ_BIKE,
                 0); -- EQ_ROW_MACHINE
crunch
curl
cycle
cycling
dog walking
double leg butt kicks
drop push-up
dynamic warm up
easy jog
explosive broad jump
fast interval
flutter kick
glute kickback
handstand hold
hanging knee raise
high intensity interval
high knee
hiking
hill interval
inverted pull-up
isometric lunge hold
isometric wiper
jog
jump rope
jumping jack
jumping lunge
kettle bell 1-arm overhead farmer’s carry
kettle bell swing
laying leg raise
long run
mountain climber
muscle-up
pistol squat
plank
plyometric push-up
power skip backward
power skip explosive
pull-up
recover
reverse bear crawl
rope climb
row
run
sandbag slam
sandbag squat
sandbag squat throw
shuttle run
side kick
side plank
side-to-side hop
sit-up
speed skater
spiderman push-up
squat jump
star jump
stretch
swimming
trail run
tricep overhead extension
uphill dash
vertical jump
walk
walking lunge
wide push-up
yoga
